version: '3.8'

services:
  educa-games-api:
    build: .
    env_file:
      - .env
    container_name: educa-games-api
    ports:
      - "8080:8080"
    depends_on:
      - educa-games-postgres
      - educa-games-mailhog
    networks:
      - educa-games-network
    restart: unless-stopped

  educa-games-postgres:
    image: postgres:15-alpine
    container_name: educa-games-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - educa-games-network
    restart: unless-stopped

  educa-games-mailhog:
    image: mailhog/mailhog:latest
    container_name: educa-games-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - educa-games-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  educa-games-network:
    driver: bridge
