spring.application.name=educagames-api

# Cookie - PRODUÇÃO
cookie.max-age=3600
cookie.secure=true
cookie.same-site=Strict
server.servlet.session.cookie.domain=.educagames.com

#Logging
logging.level.org.springframework.security=INFO

# JPA PROD
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# Actuator - PRODUÇÃO
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
management.health.db.enabled=true

# CORS
cors.allowed-origins=https://educagames.com
