spring.application.name=educagames-api

# Configuração do banco de dados com variáveis de ambiente
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:educagames-db}
spring.datasource.username=${DB_USER:educagames}
spring.datasource.password=${DB_PASSWORD:educapass}

# Configurações JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging para debug
logging.level.org.springframework.boot.autoconfigure=DEBUG
