spring.application.name=educagames-api

# Cookie - DESENVOLVIMENTO
cookie.max-age=86400
cookie.secure=false
cookie.same-site=Lax

#Logging
logging.level.root=WARN
logging.level.org.springframework=WARN
logging.level.com.educagames=WARN
logging.level.org.springframework.security=DEBUG

# JPA DEV
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Actuator - DESENVOLVIMENTO
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.health.db.enabled=false

# CORS
cors.allowed-origins=http://localhost:5173
