# Cookie
cookie.max-age=3600
cookie.secure=true
cookie.same-site=Strict
server.servlet.session.cookie.domain=.educagames.com

#Logging
logging.level.root=WARN
logging.level.com.educagames=INFO

# JPA PROD
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
management.health.db.enabled=true

# Server configuration for production
server.port=${PORT:8080}
server.address=0.0.0.0
