# Cookie - DESENVOLVIMENTO
cookie.max-age=86400
cookie.secure=false
cookie.same-site=Lax

# Logging
logging.level.root=INFO
logging.level.com.educagames=DEBUG

# JPA DEV
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.health.db.enabled=false

# Flyway
spring.flyway.enabled=false

# Errors
server.error.include-stacktrace=always
