spring.application.name=educagames-api
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# Desativa a criaÁ„o autom·tica de um usu·rio padr„o pelo Spring Security
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

# Configura√ß√µes do banco de dados com vari√°veis de ambiente
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# Configura√ß√µes JPA (mover overrides por perfil para application-*.properties)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
