spring.application.name=educagames-api
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

# Desativa a criação automática de um usuário padrão pelo Spring Security
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

# Configurações do banco de dados com variáveis de ambiente
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# Configurações JPA (mover overrides por perfil para application-*.properties)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
