name: CI - EducaGames API

# Dispara o pipeline em push ou pull request para develop
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Compose
      uses: docker/setup-buildx-action@v3

    - name: Build and run containers
      run: docker compose up -d --build

    - name: Run API tests
      run: docker exec educa-games-api ./gradlew test

    - name: Check code style
      run: docker exec educa-games-api ./gradlew spotlessCheck checkstyleMain

    - name: Stop containers
      if: always()
      run: docker compose down
