name: CI - EducaGames API

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and run containers
        run: |
          docker compose build --no-cache
          docker compose up -d

      - name: Make gradlew executable
        run: docker exec educa-games-api chmod +x ./gradlew

      - name: Convert XML files to Unix format
        run: docker exec educa-games-api sh -c "apk add --no-cache dos2unix && find /app/config/checkstyle -name '*.xml' -exec dos2unix {} \;"

      - name: Check code style
        run: docker exec educa-games-api sh -c "./gradlew spotlessCheck checkstyleMain"

      - name: Stop containers
        if: always()
        run: docker compose down
